### ISSUE TITLE
Issue with variable scoping

### ISSUE THREAD

**Issue by jhford** [elenasolomon/azure-blob-storage#9]
I wrote a unit test for the provisioner and found a problem in one of the azure-blob-storage library functions:
```
  base:api Error occurred handling: /new-state/WK9_vfe7SJG-MwGp2Y4xrA, err: ReferenceError: blob is not defined, as JSON: {}, incidentId: 1accd576-57ea-416b-b5d0-55f09da4f6a8 ReferenceError: blob is not defined
    at DataContainer._callee9$ (/home/jhford/taskcluster/aws-provisioner/node_modules/azure-blob-storage/src/datacontainer.js:370:48)
    at tryCatch (/home/jhford/taskcluster/aws-provisioner/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/jhford/taskcluster/aws-provisioner/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/jhford/taskcluster/aws-provisioner/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/home/jhford/taskcluster/aws-provisioner/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/jhford/taskcluster/aws-provisioner/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
    at process._tickDomainCallback (internal/process/next_tick.js:129:7) +489ms
```

The relevant section of code is here:

```
  async load(blobName, cacheContent) {
    assert(blobName, 'The name of the blob must be specified.');

    try {
      let blob;
      let options = {
        name: blobName,
        container: this,
        cacheContent: cacheContent,
      };
      // find the type of the blob
      let properties = await this.blobService.getBlobProperties(this.name, blobName);
      if (properties.type === 'BlockBlob') {
        blob = new DataBlockBlob(options);
      } else if (properties.type === 'AppendBlob') {
        return new AppendDataBlob(options);
      } else {
        // PageBlob is not supported
        return null;
      }

      await blob.load();
      return blob;
    } catch (error) {
      rethrowDebug(`Failed to load the blob '${blob}' from container "${this.name}" with error: ${error}`, error);
    }
  }
```
The issue is that the `${blob}` variable is scoped only in the `try{}` block.  I suspect you meant the `blobName` variable from the function?  Can you please double check other uses of rethrowDebug to make sure they don't also have this behaviour?

**Comment by jhford** [comment]
This issue was resolve with https://github.com/elenasolomon/azure-blob-storage/commit/a5807235bd26cbea30c44ef78ded9eaae3b76a88
